require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - "tmp/*"
    - "bin/*"
    - "db/**/*"
    - "config/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "node_modules/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false
