version: "3"
services:
  web:
    build: 
      context: ./application
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./application:/application
    ports:
      - "4000:3000"