version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
  database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data