default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  host: localhost
  username: pguser
  password: postgres

development:
  <<: *default
  database: nx_challenge_development

test:
  <<: *default
  database: nx_challenge_test

production:
  <<: *default
  database: nx_challenge_production