# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

local: &local
  <<: *default
  username: default
  password: default
  host: 127.0.0.1
  port: 3306

development:
  <<: *local
  database: nx_challenge_development

test:
  <<: *local
  database: nx_challenge_development_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
