default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: nex
  password: nex

  timeout: 5000

development:
  <<: *default
  database: nex

  username: nex
  password: nex
  host: db

test:
  <<: *default
  database: nex

  host: db
  username: nex
  password: nex

production:
  <<: *default
  database: nex

  host: db
  username: nex
  password: nex
